
create table agricultor
(
    id      serial       not null primary key,
    nome    varchar(255) not null,
    contato varchar(255) not null
);

create table tipoalimento
(
    id   serial       not null primary key,
    nome varchar(255) not null
);

create table edital
(
    id         serial       not null primary key,
    observacao varchar(255),
    nome       varchar(255) not null
);


create table usuario
(
    id    serial       not null primary key,
    nome  varchar(255) not null,
    email varchar(100) not null unique,
    senha varchar(255) not null
);

create table entrega
(
    id          serial      not null primary key,
    dataentrega timestamptz not null,
    edital_id    int         not null,
    usuario_id   int         not null,


    foreign key (edital_id) references edital (id),
    foreign key (usuario_id) references usuario (id)
);

create table produtoentrega
(
    id           serial      not null primary key,
    qtd          int         not null,
    tipound      varchar(32) not null,
    observacao   varchar(255),
    tipo_id       int         not null,
    entrega_id    int         not null,
    agricultor_id int         not null,

    foreign key (agricultor_id) references agricultor (id),
    foreign key (tipo_id) references tipoalimento (id),
    foreign key (entrega_id) references entrega (id)
);

create table cronograma
(
    id              serial      not null primary key,
    qtd             int         not null,
    tipound         varchar(32) not null,
    observacao      varchar(255),
    previsaoentrega timestamptz not null,
    tipo_id          int,

    foreign key (tipo_id) references tipoalimento (id)
);


insert into tipoalimento(nome)
values ('Abacate, cru'),
       ('Abacaxi, banana e cenoura, suco natural (néctar), s/ açúcar'),
       ('Abacaxi, cru'),
       ('Abacaxi, melão e maracujá, suco natural (néctar), s/ açúcar'),
       ('Abacaxi, polpa, congelada'),
       ('Abacaxi, polpa, congelada'),
       ('Abacaxi, suco natural (néctar), s/ açúcar'),
       ('Abadejo, filé, congelado, cru'),
       ('Abiu, cru'),
       ('Abóbora, menina brasileira, crua'),
       ('Abóbora, moranga, crua'),
       ('Abóbora, pescoço, crua'),
       ('Abobrinha, italiana, crua'),
       (' Abobrinha, paulista, crua'),
       ('Açafrão'),
       ('Açaí, polpa, congelada'),
       ('Acelga, crua'),
       ('Acerola, crua'),
       ('Acerola, polpa, congelada'),
       ('Acerola, suco natural (néctar), s/ açúcar'),
       ('Achocolatado em pó diet'),
       ('Açúcar, cristal'),
       ('Açúcar, mascavo'),
       ('Açúcar, refinado'),
       ('Adoçante artificial'),
       ('Agrião, cru'),
       ('Água de coco'),
       ('Aipo, cru'),
       ('Alface, americana, crua'),
       ('Alface, crespa, crua'),
       ('Alface, lisa, crua'),
       ('Alface, roxa, crua'),
       ('Alfavaca, crua'),
       ('Alho, cru'),
       ('Alho-poró, cru'),
       ('Almeirão, cru'),
       ('Almôndega, frango, crua'),
       ('Ameixa, crua'),
       ('Amêndoa, torrada, salgada'),
       ('Amendoim, grão, cru'),
       ('Amendoim, torrado, salgado'),
       ('Araçá'),
       ('Arroz, farelo'),
       ('Arroz, integral, cru'),
       ('Arroz, tipo 1, cru'),
       ('Arroz, tipo 2, cru'),
       ('Aspargo, cru'),
       ('Atemóia, crua'),
       ('Atum, fresco, cru'),
       ('Aveia, flocos, crua'),
       ('Azeite, de dendê'),
       ('Azeite, de oliva, extra virgem'),
       ('Bacalhau, salgado, cru'),
       ('Bacuri'),
       ('Banana, da terra, crua'),
       ('Banana, figo, crua'),
       ('Banana, maçã, crua'),
       ('Banana, nanica, crua'),
       ('Banana, ouro, crua'),
       ('Banana, pacova, crua'),
       ('Banana, prata, crua'),
       ('Banha suína'),
       ('Batata, baroa, crua'),
       ('Batata, doce, crua'),
       ('Batata, inglesa, crua'),
       ('Berinjela, crua'),
       ('Beterraba, crua'),
       ('Bisteca bovina (crua)'),
       ('Brócolis, cru'),
       ('Broto de alfafa'),
       ('Butiá'),
       ('Cação, posta, crua'),
       ('Cacau, cru'),
       ('Café'),
       ('Café solúvel capuccino'),
       ('Café, pó, torrado'),
       ('Cajá, polpa, congelada'),
       ('Cajá, polpa, congelada'),
       ('Cajá-Manga, cru'),
       ('Caju, cru'),
       ('Caju, polpa, congelada'),
       ('Caju, polpa, congelado'),
       ('Caju, suco concentrado, envasado'),
       ('Camarão, Rio Grande, grande, cozido'),
       ('Camarão, Rio Grande, grande, cru'),
       ('Camarão, Sete Barbas, sem cabeça, com casca, frito'),
       ('Cana-de-açúcar'),
       ('Canela em pó'),
       ('Canjica, branca, crua'),
       ('Caqui, chocolate, cru'),
       ('Cará, cru'),
       ('Carambola, crua'),
       ('Caranguejo, cozido'),
       ('Carne de bode/caprino'),
       ('Carne de caprino'),
       ('Carne de ovelha'),
       ('Carne de pato'),
       ('Carne de sol'),
       ('Carne moída'),
       ('Carne, avestruz, crua (média de diferentes cortes)'),
       ('Carne, bovina, acém, moído, cru'),
       ('Carne, bovina, acém, sem gordura, cru'),
       ('Carne, bovina, almôndegas, cruas'),
       ('Carne, bovina, bucho, cru'),
       ('Carne, bovina, capa de contra-filé, com gordura, crua'),
       ('Carne, bovina, capa de contra-filé, sem gordura, crua'),
       ('Carne, bovina, charque, cru'),
       ('Carne, bovina, contra-filé de costela, cru'),
       ('Carne, bovina, contra-filé, com gordura, cru'),
       ('Carne, bovina, contra-filé, sem gordura, cru'),
       ('Carne, bovina, costela, crua'),
       ('Carne, bovina, coxão duro, sem gordura, cru'),
       ('Carne, bovina, coxão mole, sem gordura, cru'),
       ('Carne, bovina, cupim, cru'),
       ('Carne, bovina, fígado, cru'),
       ('Carne, bovina, filé mingnon, sem gordura, cru'),
       ('Carne, bovina, flanco, sem gordura, cru'),
       ('Carne, bovina, fraldinha, com gordura, crua'),
       ('Carne, bovina, lagarto, cru'),
       ('Carne, bovina, língua, crua'),
       ('Carne, bovina, maminha, crua'),
       ('Carne, bovina, miolo de alcatra, sem gordura, cru'),
       ('Carne, bovina, músculo, sem gordura, cru'),
       ('Carne, bovina, paleta, com gordura, crua'),
       ('Carne, bovina, paleta, sem gordura, crua'),
       ('Carne, bovina, patinho, sem gordura, cru'),
       ('Carne, bovina, peito, sem gordura, cru'),
       ('Carne, bovina, picanha, com gordura, crua'),
       ('Carne, bovina, picanha, sem gordura, crua'),
       ('Carne, bovina, seca, crua'),
       ('Carne, frango, caipira, inteiro, c/ pele, cozida, Gallus gallus'),
       ('Carne, frango, caipira, inteiro, s/ pele, cozida, Gallus gallus'),
       ('Caruru, cru'),
       ('Castanha-de-caju, torrada, salgada'),
       ('Castanha-do-Brasil, crua'),
       ('Catalonha, crua'),
       ('Cebola, crua'),
       ('Cebolinha, crua'),
       ('Cenoura, crua'),
       ('Cereais, milho, flocos, com sal'),
       ('Cereais, milho, flocos, sem sal'),
       ('Cereal matinal, milho'),
       ('Chá (preto, camomila, erva-cidreira, capim-limão, etc.)'),
       ('Chá mate orgânico'),
       ('Chambaril'),
       ('Cheiro verde (50% cebolinha verde, 50% salsa), cru'),
       ('Chicória, crua'),
       ('Chuchu, cru'),
       ('Ciriguela, crua'),
       ('Coco fresco ralado'),
       ('Coco seco ralado'),
       ('Coco, cru'),
       ('Coentro'),
       ('Coentro, folhas desidratadas'),
       ('Corimba, cru'),
       ('Corvina de água doce, crua'),
       ('Corvina do mar, crua'),
       ('Couve, manteiga, crua'),
       ('Couve-flor, crua'),
       ('Creme de Leite'),
       ('Cupuaçu, cru'),
       ('Cupuaçu, polpa, congelada'),
       ('Cupuaçu, polpa, congelada'),
       ('Dourada de água doce, fresca'),
       ('Ervilha em grão'),
       ('Ervilha, em vagem'),
       ('Espinafre, Nova Zelândia, cru'),
       ('Farinha de tapioca/beiju'),
       ('Farinha, de arroz, enriquecida'),
       ('Farinha, de centeio, integral'),
       ('Farinha, de mandioca, crua'),
       ('Farinha, de mandioca, torrada'),
       ('Farinha, de mesocarpo de babaçu, crua'),
       ('Farinha, de milho, amarela'),
       ('Farinha, de puba'),
       ('Farinha, de rosca'),
       ('Farinha, de trigo'),
       ('Fava (em grão)'),
       ('Fécula, de mandioca'),
       ('Feijão (preto, mulatinho, roxo, rosinha, etc.)'),
       ('Feijão, broto, cru'),
       ('Feijão, carioca, cru'),
       ('Feijão, fradinho, cru'),
       ('Feijão, jalo, cru'),
       ('Feijão, preto, cru'),
       ('Feijão, rajado, cru'),
       ('Feijão, rosinha, cru'),
       ('Feijão, roxo, cru'),
       ('Feijão-verde'),
       ('Fermento em pó, químico'),
       ('Fermento, biológico, levedura, tablete'),
       ('Fibra de trigo'),
       ('Figo, cru'),
       ('Filé de frango'),
       ('Frango, asa, com pele, crua'),
       ('Frango, coração, cru'),
       ('Frango, coxa, com pele, crua'),
       ('Frango, coxa, sem pele, crua'),
       ('Frango, fígado, cru'),
       ('Frango, inteiro, com pele, cru'),
       ('Frango, inteiro, sem pele, cru'),
       ('Frango, peito, com pele, cru'),
       ('Frango, peito, sem pele, cru'),
       ('Frango, sobrecoxa, com pele, crua'),
       ('Frango, sobrecoxa, sem pele, crua'),
       ('Fruta-pão, crua'),
       ('Gergelim, semente'),
       ('Goiaba, branca, com casca, crua'),
       ('Goiaba, vermelha, com casca, crua'),
       ('Goiaba, vermelha, suco natural (néctar), s/ açúcar'),
       ('Grão-de-bico, cru'),
       ('Graviola, crua'),
       ('Graviola, polpa, congelada'),
       ('Graviola, polpa, congelada'),
       ('Guandu, cru'),
       ('Hortelã'),
       ('Inhame, cru'),
       ('Iogurte desnatado'),
       ('Iogurte natural'),
       ('Iogurte, integral (média de diferentes sabores)'),
       ('Iogurte, natural'),
       ('Iogurte, natural, desnatado'),
       ('Jabuticaba, crua'),
       ('Jaca, crua'),
       ('Jambo, cru'),
       ('Jamelão, cru'),
       ('Jenipapo'),
       ('Jiló, cru'),
       ('Jurubeba, crua'),
       ('Kiwi, cru'),
       ('Lambari, congelado, cru'),
       ('Lambari, fresco, cru'),
       ('Laranja e acerola, suco natural (néctar), s/ açúcar'),
       ('Laranja e mamão, suco natural (néctar), s/ açúcar'),
       ('Laranja, baía, crua'),
       ('Laranja, baía, suco'),
       ('Laranja, da terra, crua'),
       ('Laranja, da terra, suco'),
       ('Laranja, lima, crua'),
       ('Laranja, lima, suco'),
       ('Laranja, mamão, pêra e maçã, suco natural (néctar), s/ açúcar'),
       ('Laranja, pêra, crua'),
       ('Laranja, pêra, suco'),
       ('Laranja, Seleta, in natura, Citrus aurantium L.'),
       ('Laranja, valência, crua'),
       ('Laranja, valência, suco'),
       ('Lasanha, massa fresca, cozida'),
       ('Lasanha, massa fresca, crua'),
       ('Leite de soja em pó'),
       ('Leite, de cabra'),
       ('Leite, de coco'),
       ('Leite, de vaca, desnatado, pó'),
       ('Leite, de vaca, desnatado, UHT'),
       ('Leite, de vaca, integral'),
       ('Leite, de vaca, integral, pó'),
       ('Lentilha, crua'),
       ('Limão, cravo, suco'),
       ('Limão, galego, suco'),
       ('Limão, tahiti, cru'),
       ('Linhaça, semente'),
       ('Maçã, Argentina, com casca, crua'),
       ('Maçã, Fuji, com casca, crua'),
       ('Macarrão, trigo, cru'),
       ('Macarrão, trigo, cru, com ovos'),
       ('Macaúba, crua'),
       ('Mamão, Formosa, cru'),
       ('Mamão, Papaia, cru'),
       ('Mamão, suco natural (néctar), s/ açúcar'),
       ('Mandioca, crua'),
       ('Mandioca, farofa, temperada'),
       ('Manga, Haden, crua'),
       ('Manga, Palmer, crua'),
       ('Manga, polpa, congelada'),
       ('Manga, suco natural (néctar), s/ açúcar'),
       ('Manga, Tommy Atkins, crua'),
       ('Mangaba'),
       ('Manjericão, cru'),
       ('Manteiga, com sal'),
       ('Manteiga, sem sal'),
       ('Maracujá, cru'),
       ('Maracujá, polpa, congelada'),
       ('Maracujá, polpa, congelada'),
       ('Maracujá, suco concentrado, envasado'),
       ('Massa, fresca, crua'),
       ('Maxixe, cru'),
       ('Melancia e acerola, suco natural (nectar), s/ açúcar '),
       ('Melancia, crua'),
       ('Melão, cru'),
       ('Melão, suco natural (néctar), s/ açúcar'),
       ('Merluza, filé, cru'),
       ('Mexerica, Murcote, crua'),
       ('Mexerica, Rio, crua'),
       ('Milho (em grão) cru'),
       ('Milho, amido, cru'),
       ('Milho, fubá, cru'),
       ('Milho, pipoca, grãos cru'),
       ('Milho, verde, cru'),
       ('Mini pizza semi pronta (crua)'),
       ('Moela de galinha ou frango'),
       ('Molho, p/ salada, c/ salsa, suco de limão, azeite de oliva, c/ sal'),
       ('Molho, p/ salada, c/ salsa, vinagre de maçã, azeite de oliva, c/ sal'),
       ('Morango, cru'),
       ('Morango, suco natural (néctar), s/ açúcar'),
       ('Mostarda, folha, crua'),
       ('Nabo, cru'),
       ('Nata'),
       ('Nectarina'),
       ('Nêspera, crua'),
       ('Noz, crua'),
       ('Óleo, algodão, Gossypium ssp'),
       ('Óleo, de babaçu'),
       ('Óleo, de canola'),
       ('Óleo, de girassol'),
       ('Óleo, de milho'),
       ('Óleo, de pequi'),
       ('Óleo, de soja'),
       ('Orégano'),
       ('Ovo, de codorna, inteiro, cru'),
       ('Ovo, de galinha, inteiro, cru'),
       ('Ovo, galinha, clara, desidratada, pasteurizada'),
       ('Ovo, galinha, gema, desidratada, pasteurizada'),
       ('Ovo, galinha, integral, desidratada, pasteurizada'),
       ('Palma'),
       ('Palmito in natura cru'),
       ('Pamonha'),
       ('Pamonha, barra para cozimento, pré-cozida'),
       ('Peixe, água doce, tilápia, filé, cru, Oreochromis niloticus'),
       ('Pepino, cru'),
       ('Pequi, cru'),
       ('Pêra, Park, crua'),
       ('Pêra, Williams, crua'),
       ('Peru, congelado, cru'),
       ('Pescada, branca, crua'),
       ('Pescada, filé, cru'),
       ('Pescadinha, crua'),
       ('Pêssego, Aurora, cru'),
       ('Pimenta em pó'),
       ('Pimentão, amarelo, cru'),
       ('Pimentão, verde, cru'),
       ('Pimentão, vermelho, cru'),
       ('Pinha, crua'),
       ('Pinhão'),
       ('Pintado, assado'),
       ('Pintado, cru'),
       ('Pitanga, crua'),
       ('Pitanga, polpa, congelada'),
       ('Pitanga, polpa, congelada'),
       ('Polenta, pré-cozida'),
       ('Polvilho, doce'),
       ('Porco, bisteca, crua'),
       ('Porco, bisteca, frita'),
       ('Porco, costela, crua'),
       ('Porco, lombo, cru'),
       ('Porco, pernil, cru'),
       ('Porquinho, cru'),
       ('Queijo colonial'),
       ('Queijo de coalho'),
       ('Queijo ralado'),
       ('Queijo, minas, frescal'),
       ('Queijo, minas, meia cura'),
       ('Queijo, mozarela'),
       ('Queijo, parmesão'),
       ('Queijo, pasteurizado'),
       ('Queijo, prato'),
       ('Queijo, requeijão, cremoso'),
       ('Queijo, ricota'),
       ('Quiabo, cru'),
       ('Quinoa, crua'),
       ('Quirera não especificada'),
       ('Rabanete, cru'),
       ('Repolho, branco, cru'),
       ('Repolho, roxo, cru'),
       ('Romã, crua'),
       ('Rúcula, crua'),
       ('Sal, dietético'),
       ('Sal, grosso'),
       ('Salmão, sem pele, fresco, cru'),
       ('Salsa, crua'),
       ('Salsinha'),
       ('Salsinha seca'),
       ('Sapoti'),
       ('Sardinha, inteira, crua'),
       ('Serralha, crua'),
       ('Soja, extrato solúvel, natural, fluido'),
       ('Soja, extrato solúvel, pó'),
       ('Soja, farinha'),
       ('Soja, queijo (tofu)'),
       ('Taioba, crua'),
       ('Tamarindo, cru'),
       ('Tangerina, Poncã, crua'),
       ('Tangerina, Poncã, suco'),
       ('Taperebá'),
       ('Tomate seco'),
       ('Tomate, com semente, cru'),
       ('Tomate, extrato'),
       ('Tomate, purê'),
       ('Tomate, salada'),
       ('Tortas salgadas de qualquer sabor'),
       ('Toucinho, cru'),
       ('Tremoço, cru'),
       ('Trigo para quibe, cru, Triticum spp.'),
       ('Trigo, farelo'),
       ('Tucumã, cru'),
       ('Tucunaré, filé, congelado, cru'),
       ('Umbu, cru'),
       ('Umbu, polpa, congelada'),
       ('Umbu, polpa, congelada'),
       ('Uva passa'),
       ('Uva, Itália, crua'),
       ('Uva, Rubi, crua'),
       ('Uva, suco concentrado, envasado'),
       ('Vagem, crua'),
       ('Vinagre, maçã'),
       ('Víscera bovina'),
       ('Xérem de milho');